name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command '...'
        2. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Collector Agent
        - Zeitgeist Agent
        - Collectors (Celebrity Tracker)
        - Collectors (Network Press)
        - Collectors (Entertainment News)
        - Collectors (Reality Show Controversy)
        - Collectors (YouTube Engagement)
        - Envy Toolkit
        - CI/CD Pipeline
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide information about your environment:
        - OS (Windows/Mac/Linux)
        - Python version
        - Poetry version
        - Docker version (if applicable)
      placeholder: |
        OS: Ubuntu 20.04
        Python: 3.11.5
        Poetry: 1.7.1
        Docker: 24.0.0
    validations:
      required: true