# Production Security Configuration for Perfect Collector System
# This file contains critical security settings and limits

# Database Security
database:
  max_connections: 20
  connection_timeout_seconds: 30
  query_timeout_seconds: 60
  max_batch_size: 50
  enable_query_logging: true
  enable_slow_query_logging: true
  slow_query_threshold_ms: 1000

# Memory and Resource Limits  
resources:
  max_memory_mb: 512
  max_cpu_percent: 80
  max_disk_usage_gb: 10
  max_concurrent_operations: 10
  enable_resource_monitoring: true

# Rate Limiting Configuration
rate_limits:
  reddit_api:
    requests_per_minute: 60
    burst_size: 10
    cooldown_seconds: 60
  
  serpapi:
    requests_per_minute: 100
    burst_size: 20
    cooldown_seconds: 30
  
  google_trends:
    requests_per_minute: 30
    burst_size: 5
    cooldown_seconds: 120
  
  discovery_api:
    requests_per_minute: 30
    burst_size: 5
    cooldown_seconds: 180

# Input Validation
validation:
  max_subreddit_name_length: 100
  max_description_length: 500
  max_title_length: 300
  max_body_length: 5000
  max_url_length: 2000
  max_array_size: 100
  max_mentions_per_batch: 1000
  max_discovery_results: 50

# Storage Tier Limits
storage_tiers:
  hot_storage:
    max_mentions_per_day: 10000
    max_size_mb: 1000
  
  warm_storage:
    max_mentions_per_day: 50000
    max_size_mb: 5000
    ttl_days: 7
  
  cold_storage:
    max_batch_size_mb: 50
    compression_enabled: true
    storage_class: "STANDARD_IA"

# Security Settings
security:
  enable_input_sanitization: true
  enable_sql_injection_protection: true
  enable_xss_protection: true
  enable_csrf_protection: true
  max_login_attempts: 5
  session_timeout_minutes: 60
  require_https: true
  
  # Content Security
  allowed_domains:
    - "reddit.com"
    - "twitter.com" 
    - "x.com"
    - "tiktok.com"
    - "instagram.com"
    - "tmz.com"
    - "pagesix.com"
    - "variety.com"
    - "deadline.com"
    - "hollywoodreporter.com"
    - "people.com"
    - "usmagazine.com"
    - "eonline.com"
    - "justjared.com"
    - "vulture.com"
    - "buzzfeed.com"
    - "popsugar.com"
    - "refinery29.com"
    - "cosmopolitan.com"
    - "elle.com"
    - "youtube.com"
    - "dailymail.co.uk"
    - "thesun.co.uk"
    - "mirror.co.uk"
    - "metro.co.uk"
    - "nbc.com"
    - "abc.com"
    - "fox.com"
    - "bravotv.com"
    - "wetv.com"
    - "tlc.com"
    - "entertainmentweekly.com"
    - "rollingstone.com"
    - "billboard.com"
    - "pitchfork.com"

# Monitoring and Alerting
monitoring:
  enable_health_checks: true
  health_check_interval_seconds: 60
  enable_performance_monitoring: true
  enable_error_tracking: true
  enable_audit_logging: true
  
  # Alert Thresholds
  alerts:
    high_error_rate_percent: 10
    high_response_time_ms: 5000
    low_success_rate_percent: 80
    high_memory_usage_percent: 90
    high_cpu_usage_percent: 85
    database_connection_failures: 5

# Backup and Recovery
backup:
  enable_database_backup: true
  backup_interval_hours: 6
  retention_days: 30
  enable_point_in_time_recovery: true
  
# Circuit Breaker Configuration
circuit_breakers:
  database:
    failure_threshold: 5
    timeout_seconds: 60
    half_open_max_calls: 3
  
  external_api:
    failure_threshold: 10
    timeout_seconds: 120
    half_open_max_calls: 5

# Burst Scheduler Security
burst_scheduler:
  max_triggers_per_hour: 10
  max_concurrent_collections: 3
  max_burst_duration_hours: 12
  cooldown_between_bursts_minutes: 30

# Discovery System Security  
discovery:
  max_discoveries_per_session: 50
  max_validation_attempts: 3
  require_manual_approval: true
  enable_auto_integration: false  # Disabled for security
  validation_cooldown_hours: 24

# Logging Configuration
logging:
  level: "INFO"
  enable_structured_logging: true
  enable_sensitive_data_masking: true
  max_log_file_size_mb: 100
  max_log_files: 10
  enable_log_rotation: true
  
  # Security Event Logging
  security_events:
    - "authentication_failure"
    - "authorization_failure" 
    - "injection_attempt"
    - "rate_limit_exceeded"
    - "suspicious_activity"
    - "configuration_change"
    - "privilege_escalation"

# Environment-Specific Settings
environments:
  production:
    debug_mode: false
    enable_profiling: false
    strict_validation: true
    
  staging:
    debug_mode: true
    enable_profiling: true
    strict_validation: true
    
  development:
    debug_mode: true
    enable_profiling: true
    strict_validation: false